allowBuilds:
  esbuild: true

overrides:
  path-to-regexp: 8.4.2
  on-headers: 1.1.0
  picomatch: 4.0.4
  postcss: 8.5.23
  qs: 6.15.2
  rollup: 4.61.1
  socket.io-parser: 4.2.7
  vite: 7.3.5
  ws: 8.21.3
  esbuild: 0.28.1

shellEmulator: true
