onlyBuiltDependencies:
  - core-js
  - esbuild

overrides:
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  on-headers@<1.1.0: '>=1.1.0'
  vite@>=7.1.0 <=7.1.10: '>=7.1.11'
  vite@>=7.1.0 <=7.1.4: '>=7.1.5'

shellEmulator: true
